### ISSUE TITLE
in producer, support message rotuting

### ISSUE THREAD

**Issue by wolfstudy** [wolfstudy/pulsar-client-go#22]
**Describe alternatives you've considered**

Set the message routing mode for the partitioned producer, default routing mode is round-robin routing.

MessageRoutingMode:

- SinglePartition
- RoundRobinPartition
- CustomPartition

for specific functional descriptions, refer to: [message routing](https://pulsar.apache.org/api/client/org/apache/pulsar/client/api/ProducerBuilder.html#messageRoutingMode-org.apache.pulsar.client.api.MessageRoutingMode-)

**Comment by zhvala** [comment]
[Message-rotuting](https://github.com/wolfstudy/pulsar-client-go/issues/22) and [auto update-partitions-support](https://github.com/wolfstudy/pulsar-client-go/issues/23) may be the highest priority features if someone want to use this client to produce data in a  pulsar cluster which has multi-partition topics.

**Comment by wolfstudy** [comment]
java client impl:[https://github.com/apache/pulsar/pull/1089/files](https://github.com/apache/pulsar/pull/1089/files)
